sudo: false
language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler -v '< 2'

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: truffleruby
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
