#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "./chat"
require "rack"
require "anycable"

# Turn AnyCable compatibility mode
LiteCable.anycable!

Anycable.connection_factory = Chat::Connection

Anycable::Server.start
