# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "slim"

gem "puma"

gem "pry-byebug"

# litecable deps
gem "litecable", path: "../../"

# For Rack/Puma server
gem "websocket", "~> 1.2.4"

# For AnyCable
gem "anycable", "1.0.0.rc1"
