source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'

gem 'puma'

gem 'pry-byebug'

# litecable deps
gem "anyway_config", "~> 1.0"
gem "websocket", "~> 1.2.4"

# anycable
gem "anycable", "~> 0.5.0"
